### ISSUE TITLE
Feature Request: Support attaching to remote targets (VM's etc)

### ISSUE THREAD

**Issue by KnisterPeter** [Microsoft/vscode-edge-debug#10]
Since I'm a linux user but need to debug edge from time to time it would be awesome to have my edge running inside a VM (e.g. virtualbox) and attach from my host (linux) into the edge browser.

**Comment by auchenberg** [comment]
Great idea. Hereby added to the backlog.

**Comment by hun1ahpu** [comment]
Hey guys.

Is it still in the backlog? I have no idea how difficult it is but always ready to contribute :)

Thanks.
