### ISSUE TITLE
Debugger breaks while trying to attach to Edge

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode-edge-debug#11]
I'm unable to connect the debugger to an open Edge window.
Also opening an Edge window via URL breaks the debugger, the Edge window opens with the correct url but the debugger fails.

**Comment by auchenberg** [comment]
Can I get you to paste in your `launch.json` config and the log after setting `diagnosticLogging` to `true` on the config?

**Comment by ghost** [comment]
No problem. But, since there is no option to copy everything from the Debug Console, I eliminated the massive amount of duplicates.
```JSON
{
    "version": "0.2.0",
    "configurations": [{
        "name": "Launch localhost with sourcemaps",
        "type": "edge",
        "request": "launch",
        "url": "<url>/main.aspx?etc=1&extraqs=formid%3d8448b78f-8f42-454e-8e2a-f8196b0419af&id=%7b31421CA8-AFBE-E511-80C5-00155DF7EA33%7d&pagetype=entityrecord",
        "webRoot": "${workspaceRoot}"
    }]
}
```
```
›OS: win32 ia32
  ›Node version: v6.5.0
  ›Adapter version: 0.0.5
  ›initialize({"adapterID":"edge","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true})
  ›attach({"name":"Launch localhost with sourcemaps","type":"edge","request":"launch","url":"<url>/main.aspx?etc=1&extraqs=formid%3d8448b78f-8f42-454e-8e2a-f8196b0419af&id=%7b31421CA8-AFBE-E511-80C5-00155DF7EA33%7d&pagetype=entityrecord","webRoot":"<path>","diagnosticLogging":true,"port":9222})
  ›Attempting to attach on port 9222
  ›Warning: Can't find a page with url: <url>/main.aspx?etc=1&extraqs=formid%3d8448b78f-8f42-454e-8e2a-f8196b0419af&id=%7b31421ca8-afbe-e511-80c5-00155df7ea33%7d&pagetype=entityrecord. Available pages: ["about:blank"]
[2016-12-12 08:42:50] [error] Handshake ended with HTTP error: 400
```

**Comment by auchenberg** [comment]
@con-ssc Interesting. It looks like VS Code can't find the open tab in Edge.  

Do you see a visible tab with the `url` you provided? The output says 1x `about:blank`

**Comment by ghost** [comment]
Well, know, I see the page I would expect. I have the same launch options for the chrome browser and that works as expected.

**Comment by auchenberg** [comment]
Alright. Then it seems to be a bug in our [Edge Diagnostics Adapter](https://github.com/Microsoft/edge-diagnostics-adapter), as your newly opened tab don't get exposed to VS Code.

A work around until we have a fix, could be to download the [Edge Diagnostics Adapter](https://github.com/Microsoft/edge-diagnostics-adapter, start it, and configure VS Code in attach-mode.

**Comment by ghost** [comment]
@auchenberg That workaround works. Do you know if it also works with the IE Diagnostics Adapter?

**Comment by auchenberg** [comment]
@con-ssc It should, as the architecture of the adapters are quite alike.
