### ISSUE TITLE
Cannot launch Edge with local web page 

### ISSUE THREAD

**Issue by macxfadz** [Microsoft/vscode-edge-debug#17]
This is the **launch.json** I used in my VSCode
{
    "version": "0.2.0",
    "configurations": [
        **{
              "name": "Launch edge",
              "type": "edge",
              "request": "launch",
              "file": "${workspaceRoot}/ta.html"
        }**,
        {
              "name": "Launch localhost with sourcemaps",
              "type": "edge",
              "request": "launch",
              "url": "file://C:/Users/Buddhi/Desktop/WebInterface/ta.html",
              "webRoot": "${workspaceRoot}",
              "sourceMaps":true
        },
        {
              "name": "Attach edge",
              "type": "edge",
              "request": "attach",
              "webRoot": "${workspaceRoot}", // optional: used to find the right tab running in Edge
              "port": 9222
        }
    ]
}

When I try to launch **_ta.html_** through VSCode with **_Launch edge_**  name mode VSCode giving an error  .
Please refer this image link: [VSCode error](https://ibb.co/m2qDWa)
I refer the original documentation but I cannot launch a local file from edge please help.
[Info](https://github.com/Microsoft/vscode-edge-debug)
[Link to the launch.json](https://www.dropbox.com/s/sgisatpnlvusos4/launch.json?dl=0)
**Please note that I have a launch  and debug configuration for the chrome too.It's working**

**Comment by d3r3kk** [comment]
Also seeing a problem. Using the configuration block:

```
{
  "name": "Launch index.html (without sourcemaps)",
  "type": "edge",
  "request": "launch",
  "file": "${workspaceRoot}/dist/index.html"
}
```
results in an error popup with the text:

> **[Error]** [debugger-for-chrome] Got response from target app, but no valid target pages found

Working fine in the Chrome Debugger, and the Firefox Debugger.
