### ISSUE TITLE
Add travis-ci and appveyor build to repository

### ISSUE THREAD

**Issue by dennisroche** [Microsoft/vscode-edge-debug#21]
Give confidence to merging pull requests, see `vscode-chrome-debug` as an example. 

https://github.com/Microsoft/vscode-chrome-debug

https://travis-ci.org/Microsoft/vscode-chrome-debug
https://ci.appveyor.com/project/microsoft/vscode-chrome-debug

**Comment by dhanvikapila** [comment]
This repository is deprecated and no longer maintained.  Active development has been happening on the newer Edge debugging extension at [Microsoft/vscode-edge-debug2](https://github.com/Microsoft/vscode-edge-debug2)
