### ISSUE TITLE
2048 is a clone of Threes

### ISSUE THREAD

**Issue by JAForbes** [Microsoft/vscode-edge-debug#5]
Great work on the plugin!  I have a fairly odd request.
In your readme there is a gif of debugging a game called 2048.

I'm not sure if you are aware, but 2048 was a clone of the game Threes.  Threes design was [agonized over for a long time](http://asherv.com/threes/threemails/), endlessly refined, it is a masterpiece of game design.  At the last minute it was copied, and the copy received the mindshare.

It'd be great if the publicity went to the original creators.  I'm hoping in your demo you could change the heading to Three's.

Thank you

**Comment by andysterland** [comment]
@JAForbes thanks for the context, I definitely wasn't aware of any of the history. To avoid any further complication I've update the gif to just use the Todo MVC app from the TypeScript [samples ](https://github.com/Microsoft/TypeScriptSamples/tree/master/todomvc). 

(It might take a while for the changed gif to propagate through the CDN etc.)

**Comment by JAForbes** [comment]
Thank you 🎉
