### ISSUE TITLE
Breakpoint added to ts file not working

### ISSUE THREAD

**Issue by gpehartz** [Microsoft/vscode-edge-debug#7]
When I add breakpoints to ts files in my application the breakpoint will be always unverified. The debug console contains "Not implemented" error messages.
Launch.json content:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch localhost with sourcemaps",
            "type": "edge",
            "request": "launch",
            "url": "http://localhost:8000/",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "diagnosticLogging": true
        }
    ]
}

Debug console content when adding BP in code:
›SourceMaps.setBP: Mapped c:\HPSRC\Git\Handy\Handy.Client\app\modules\search\customer-search.component.ts to c:\HPSRC\Git\Handy\Handy.Client\app\modules\search\customer-search.component.js
  ›SourceMaps.setBP: Mapped c:\HPSRC\Git\Handy\Handy.Client\app\modules\search\customer-search.component.ts:32:0 to c:\HPSRC\Git\Handy\Handy.Client\app\modules\search\customer-search.component.js:54:20
  ›SourceMaps.setBP: Mapped c:\HPSRC\Git\Handy\Handy.Client\app\modules\search\customer-search.component.ts:71:0 to c:\HPSRC\Git\Handy\Handy.Client\app\modules\search\customer-search.component.js:91:20
  ›Paths.setBP: Resolved c:\HPSRC\Git\Handy\Handy.Client\app\modules\search\customer-search.component.js to http://localhost:8000/app/modules/search/customer-search.component.js
  ›To target: {"id":5,"method":"Debugger.setBreakpointByUrl","params":{"url":"http://localhost:8000/app/modules/search/customer-search.component.js","lineNumber":54,"columnNumber":20}}
  ›To target: {"id":6,"method":"Debugger.setBreakpointByUrl","params":{"url":"http://localhost:8000/app/modules/search/customer-search.component.js","lineNumber":91,"columnNumber":20}}
  **›From target: {"id":5,"error":{"description":"Not implemented"}}
  ›From target: {"id":6,"error":{"description":"Not implemented"}}**
  ›SourceMaps.setBP: Mapped c:\HPSRC\Git\Handy\Handy.Client\app\modules\search\customer-search.component.js:54:0 to c:/HPSRC/Git/Handy/Handy.Client/app/modules/search/customer-search.component.ts:32
  ›SourceMaps.setBP: Mapped c:\HPSRC\Git\Handy\Handy.Client\app\modules\search\customer-search.component.js:91:0 to c:/HPSRC/Git/Handy/Handy.Client/app/modules/search/customer-search.component.ts:71
  ›To client: {"seq":0,"type":"response","request_seq":5,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"line":33},{"verified":false,"line":72}]}}

**Comment by auchenberg** [comment]
Hi @gpehartz,

I do apologize for not seeing this issue before. Do you still have this problem?

**Comment by roblourens** [comment]
Probably from the diagnostics adapter, not the chrome -core lib?

**Comment by auchenberg** [comment]
Most likely, looks like the error is thrown when trying to set a breakpoint in a file that isn't recognized by the adaptor. https://github.com/Microsoft/edge-diagnostics-adapter/blob/master/src/chromeProtocol/debugger.ts#L568

**Comment by gpehartz** [comment]
Yeah, i tried it today and the message is the same as before. The breakpoints are not verified.

**Comment by auchenberg** [comment]
Thanks @gpehartz.

Opened issue in the edge-diagnostics-adapter. https://github.com/Microsoft/edge-diagnostics-adapter/issues/49

**Comment by auchenberg** [comment]
@gpehartz Would you be able to provide an example app of this not working?
