### ISSUE TITLE
support sourceMapPathOverrides as Debugger for Chrome

### ISSUE THREAD

**Issue by ljqx** [Microsoft/vscode-edge-debug#8]
see https://github.com/Microsoft/vscode-chrome-debug

This config is helpful when we're using webpack, which is a common case for users.

**Comment by auchenberg** [comment]
Good suggestion @ljqx1! We should be able to add that quite easily by upgrading vscode-chrome-debug-core.

**Comment by dennisroche** [comment]
I'm interested in picking this up. What is required?

- [ ] Update `vscode-chrome-debug-core`
- [ ] Update README.md with sample `launch.json` configuration
- [ ] ... ?
