### ISSUE TITLE
Breakpoint in .ts file (Angular 2) not working

### ISSUE THREAD

**Issue by rongchaua** [Microsoft/vscode-edge-debug#9]
Hi, 
i followed the Angular 2 Quickstart instructions to make a[ sample application in TypeScript](https://bitbucket.org/rongchaua/electron-angular-2). The application can be started with "npm start" command.
But if I want to set a breaktpoint, from example in file "hero.service.ts" --> getHeroes() function. The breakpoint is always unverified. 

The debug console shows me the following

`›From client: setBreakpoints({"source":{"path":"c:\\Projects\\Deleteme\\electron-angular-2\\app\\hero.service.ts","name":"hero.service.ts"},"lines":[38],"breakpoints":[{"line":38}],"sourceModified":false})
  ›SourceMaps.setBP: Mapped c:\Projects\Deleteme\electron-angular-2\app\hero.service.ts to c:\Projects\Deleteme\electron-angular-2\app\hero.service.js
  ›SourceMaps.setBP: Mapped c:\Projects\Deleteme\electron-angular-2\app\hero.service.ts:37:0 to c:\Projects\Deleteme\electron-angular-2\app\hero.service.js:37:8
  ›Paths.setBP: Resolved c:\Projects\Deleteme\electron-angular-2\app\hero.service.js to http://localhost:3000/app/hero.service.js
  ›To target: {"id":5,"method":"Debugger.setBreakpointByUrl","params":{"url":"http://localhost:3000/app/hero.service.js","lineNumber":37,"columnNumber":8}}
  ›undefined
  ›To client: {"seq":0,"type":"response","request_seq":6,"command":"setBreakpoints","success":false,"message":"[debugger-for-chrome] undefined"}`

Steps to reproduce:
1. Checkout source code.
2. npm install
3. npm start
4. Press F5 or "Launch localhost with sourcemaps"
5. Set breakpoint at function getHeroes() in "hero.service.ts".
6. In application, click on menu "Heroes". Breakpoint can't be hold.

My launch.json

`"name": "Launch localhost with sourcemaps",
            "type": "edge",
            "request": "launch",
            "url": "http://localhost:3000/dashboard",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "diagnosticLogging": true`

**Comment by ghost** [comment]
Hey,

Had the same issue, did not find a resolution.  I did, however, find a way to debug.  After launching debug in vscode (F5), I switched to IE and hit F12 for developer mode, went to the debugger tab and set a breakpoint there.  When the flow hit the breakpoint, vscode popped up and I could walk through the code.
